name: 📢 PegRun Release Announcement
description: Create a freeform issue to announce new APK releases.
title: "[Release] "
labels: [announcement]
body:
  - type: markdown
    attributes:
      value: |
        Use this issue to announce a new PegRun APK release.  
        You can include version info, changelog, and a download link.

        👉 [Download the latest APK from GitHub Releases](https://github.com/PlagueFitnessCanada/PegRun/releases/latest)

  - type: textarea
    id: release-notes
    attributes:
      label: Release Notes
      description: Add details about the new release here.
      placeholder: Version number, changelog, fixes, etc.
