name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: "## 💡 Feature Request"
  - type: textarea
    attributes:
      label: What feature would you like to see?
  - type: textarea
    attributes:
      label: Why is this feature important?
      description: How will it improve the app or user experience?
  - type: textarea
    attributes:
      label: Additional context
      description: Any links, mockups, or examples?
