name: 💤 Report Inactive Run Club Repository
description: Help us identify run club repositories that are no longer active.
title: "[Inactive Run Club] <club-name-or-repo-name>"
labels: [inactive, run-club, needs-review]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🏃‍♂️ Inactive Run Club Report
        If you've noticed a run club repository that seems abandoned or inactive, please fill out this form so we can review it. This helps keep the running community organized and up-to-date.

  - type: input
    id: last_commit
    attributes:
      label: 📅 Last Joined Date
      description: When was the last time you attempted to join the run club?
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: textarea
    id: contact_attempts
    attributes:
      label: 📬 Attempts to Contact Club
      description: Have you tried reaching out to the Club? If so, what happened?
      placeholder: e.g. Sent a message via GitHub Discussions, no reply. Tagged maintainer in issue, no response.
    validations:
      required: false

  - type: checkboxes
    id: reasons
    attributes:
      label: 🚨 Why Are You Reporting This Run Club?
      description: Select all that apply.
      options:
        - label: Club wont respond to my inquiries
        - label: Club appears inactive or disbanded
        - label: Other (please explain below)

