name: 💤 Report Inactive Run Club Repository
description: Use this form to report a run club repository that appears inactive or abandoned.
title: "[Inactive Run Club] <repository-name>"
labels: [inactive, run-club, needs-review]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Inactive Run Club Report
        Please fill out the details below to help us assess the status of this repository.

  - type: input
    id: repo_url
    attributes:
      label: 🔗 Repository URL
      description: Paste the full GitHub URL of the run club repository.
      placeholder: https://github.com/org-name/repo-name
    validations:
      required: true

  - type: input
    id: last_commit
    attributes:
      label: 📅 Last Commit Date
      description: When was the last commit made?
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: input
    id: last_activity
    attributes:
      label: 🛠️ Last Issue or PR Activity
      description: When was the last issue or pull request activity?
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: textarea
    id: contact_attempts
    attributes:
      label: 📬 Maintainer Contact Attempts
      description: Describe any attempts to contact the maintainers and their response (if any).
      placeholder: e.g. Sent an email on Jan 1, no reply. Commented on open issue, no response.
    validations:
      required: false

  - type: checkboxes
    id: reasons
    attributes:
      label: 🚨 Reason for Reporting
      description: Select
